VERSION ?= 1.0.0
NAME := eqcodex.com

.PHONY: server
server:
	@hugo server -b http://localhost:1313/ --noHTTPCache --ignoreCache

.PHONY: build
build:
	@#rm -rf public/*
	@hugo -b https://eqcodex.com/

.PHONY: index
index:
	@docker run --rm -it -v $(PWD):/src lunr-hugo /bin/sh -c "cd lunr-index && npm install --save-dev grunt string toml js-yaml && ./node_modules/.bin/grunt lunr-index"

index-image:
	@cd lunr-index && docker build -t lunr-hugo -f lunr.docker.dev .

relogin:
	firebase logout
	firebase login
	firebase use xackery

deploy: build
	@firebase deploy

set-version:
	@echo "VERSION=${VERSION}" >> $$GITHUB_ENV

.PHONY: scss
scss:
	@(echo "/* This file is autogenerated via 'make scss'. DO NOT EDIT */" > static/css/tpe-scss.css)
	docker run --rm -v $(PWD):$(PWD) -w $(PWD) jbergknoff/sass scss/app.scss >> static/css/tpe-scss.css

.PHONY: spells
spells:
	go run scripts/spells/main.go

.PHONY: items
items:
	go run scripts/items/items.go

.PHONY: fetch
fetch:
	go run scripts/fetch/fetch.go